import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ViewBooks from "./user/viewBooks";
import { useEffect } from "react";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import Navbar from "@/components/navBar/NavBar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (!Cookies.get("user")) {
      router.push("/user/login");
      return;
    }
  });

  return (
    <>
      <Head>
        <title>GoodReads WebApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            marginTop: "60px",
          }}
        >       
          <ViewBooks />
        </div>
      </main>
    </>
  );
}
